#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  
before_build:
  - msbuild /t:Restore BlankFormsApp/BlankFormsApp.fsproj
  - msbuild /t:Restore Droid/BlankFormsApp.Droid.fsproj

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: Xamarin.Android.FSharp.ResourceProvider.sln
